import { useState } from "react";
import { Link } from "react-router-dom";
import { Gauge, Wallet, CheckCircle2, ArrowLeft } from "lucide-react";
import { Button } from "../components/ui/button";
import { Input } from "../components/ui/input";
import { Label } from "../components/ui/label";
export default function Demonstracao() {
  const [step,setStep]=useState(0), [reading,setReading]=useState("1285"), [expense,setExpense]=useState("250"), [error,setError]=useState("");
  const consumption=Number(reading)-1200, target=90;
  const labels=["Registrar água","Registrar despesa","Entender o resultado"];
  function next(e) {e.preventDefault();setError("");if(step===0 && (!reading || !Number.isFinite(Number(reading)) || Number(reading)<1200)){setError("Informe uma leitura igual ou maior que 1.200 m³.");return;}if(step===1 && (!expense || !Number.isFinite(Number(expense)) || Number(expense)<=0)){setError("Informe um valor maior que zero.");return;}setStep(step+1);}
  return <main className="max-w-3xl mx-auto px-4 py-10"><Link to="/" className="text-sm text-emerald-700 flex gap-2 items-center mb-6"><ArrowLeft className="w-4 h-4"/>Voltar ao início</Link><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">Demonstração guiada · cerca de 2 minutos</p><h1 className="text-3xl font-bold mt-3">Experimente uma rotina da fazenda</h1><p className="text-slate-500 mt-3 mb-7">Fazenda Exemplo · dados fictícios. Você pode experimentar sem criar conta. Nada é salvo nas fazendas cadastradas.</p>
    <ol className="grid sm:grid-cols-3 gap-3 mb-7">{labels.map((l,i)=><li key={l} aria-current={step===i?"step":undefined} className={`rounded-xl p-3 border text-sm ${step===i?"bg-emerald-50 border-emerald-300 text-emerald-900":"bg-white text-slate-500"}`}>{i+1}. {l}</li>)}</ol>
    <section className="bg-white border rounded-2xl p-6 sm:p-8">
      {step<2 ? <form onSubmit={next} className="space-y-5">{step===0 ? <><Gauge className="w-8 h-8 text-sky-600"/><h2 className="text-2xl font-bold">Quanto o hidrômetro marca agora?</h2><p className="text-slate-600">A leitura anterior era <strong>1.200 m³</strong>. Informe o número acumulado do hidrômetro; a diferença será o consumo do intervalo.</p><div><Label htmlFor="demo-leitura">Nova leitura (m³)</Label><Input id="demo-leitura" type="number" min={1200} step="0.01" value={reading} onChange={e=>setReading(e.target.value)} required/></div></> : <><Wallet className="w-8 h-8 text-emerald-600"/><h2 className="text-2xl font-bold">Registre a despesa de energia</h2><p role="status" className="text-emerald-700">Leitura registrada na demonstração: consumo de {consumption.toLocaleString("pt-BR")} m³.</p><p className="text-slate-600">Informe o valor da conta de energia. Isso permite acompanhar o dinheiro gasto junto dos dados da fazenda.</p><div><Label htmlFor="demo-despesa">Despesa de energia (R$)</Label><Input id="demo-despesa" type="number" min="0.01" step="0.01" value={expense} onChange={e=>setExpense(e.target.value)} required/></div></>}{error&&<p role="alert" className="text-red-700">{error}</p>}<div className="flex flex-wrap gap-3">{step>0&&<Button type="button" variant="outline" onClick={()=>setStep(step-1)}>Voltar</Button>}<Button>{step===0?"Registrar leitura e continuar":"Registrar despesa e ver resultado"}</Button></div></form> : <div><CheckCircle2 className="w-9 h-9 text-emerald-600"/><h2 className="text-2xl font-bold mt-4">Dois registros. Uma visão mais clara.</h2><div className="grid sm:grid-cols-2 gap-4 my-6"><div className="bg-sky-50 rounded-xl p-5"><p className="text-sm text-slate-500">Consumo do intervalo</p><p className="text-3xl font-bold mt-2">{consumption.toLocaleString("pt-BR")} m³</p><p className="text-sm mt-2">Meta ilustrativa: {target} m³</p></div><div className="bg-emerald-50 rounded-xl p-5"><p className="text-sm text-slate-500">Despesa registrada</p><p className="text-3xl font-bold mt-2">{Number(expense).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</p><p className="text-sm mt-2">Energia elétrica</p></div></div><p className="font-semibold">{consumption<=target?"Consumo dentro da meta do exemplo.":"Consumo acima da meta do exemplo."}</p><p className="text-slate-600 mt-2 leading-relaxed">{consumption<=target?"Continue registrando as leituras para acompanhar a evolução.":"O próximo passo é conferir vazamentos e mudanças na rotina antes de concluir a causa."} Na conta real, o histórico fica disponível para você e para a prefeitura, e pode ser exportado em PDF.</p><div className="flex flex-wrap gap-3 mt-7"><Button asChild><Link to="/cadastro">Cadastrar minha fazenda</Link></Button><Button variant="outline" onClick={()=>{setStep(0);setReading("1285");setExpense("250");setError("");}}>Recomeçar demonstração</Button></div></div>}
    </section>
  </main>;
}
